### ISSUE TITLE
Version 2.1.1 causes performance issues

### ISSUE THREAD

**Issue by MattCzerner** [snc/SncRedisBundle#417]
Hi, after upgrading to newest 2.1.1 our applications performance fell down radically. After downgrading to 2.1.0, everything is okay.

**Comment by terox** [comment]
We are experiencing the same issue. The ```Symfony\Bundle\SecurityBundle\EventListener\FirewallListener``` execution time is high.

**Comment by curry684** [comment]
Also, are you using phpredis extension or Predis? That should eliminate some possible causes.

**Comment by curry684** [comment]
#412 would be the likely culprit as it affects session handling.

**Comment by terox** [comment]
@curry684 we are using the phpredis extension and we are handling sessions at redis server.

We still trying to found a solution.

**Comment by curry684** [comment]
I just pushed a revert of #412 to 2.1 to disable destructor calls, can you try `2.1.x-dev`?

**Comment by jeromehubert** [comment]
Hi,
We are also having this issue.
`2.1.x-dev` doesn't seem to fix it...

**Comment by curry684** [comment]
I'm pretty stumped on what would then be causing it, diff between 2.1.0 and 2.1.x-dev is [not that invasive](https://github.com/snc/SncRedisBundle/compare/2.1.0...2.1).

I do wonder however about the serialization option we introduced. I was under the impression that it would be transparent if unconfigured, but rereading the code it does seem that before it did not serialize anything, and the default is now to use `php` serialization. This should be minimal to no impact, but it could be a difference. So, does explicitly setting serialization to `none` fix it?

**Comment by curry684** [comment]
Also, for all people reporting performance issues, I am assuming the performance degradation is in an environment *without* logging, and please do add whether using phpredis or Predis to pinpoint the culprit.

**Comment by jeromehubert** [comment]
We are using phpredis.
Yes, serialization seems to be the problem. Setting it to false make it much faster (as it was before).

**Comment by phansys** [comment]
Same to me, using `snc_redis.clients.session.options.serialization: false` with PhpRedis the performance issues are gone.

**Comment by yellow1912** [comment]
In that case if this is confirmed I can push a change to make serialization to none by default.

**Comment by curry684** [comment]
Will merge and release 2.1.2 if you do, thanks   👍

**Comment by curry684** [comment]
Nevermind, pushed it in https://github.com/snc/SncRedisBundle/commit/ed4c92563058dc1d3824c8c7c8ec50aaaf4f270c as I had to make other changes.

**Comment by curry684** [comment]
And off we go: https://github.com/snc/SncRedisBundle/releases/tag/2.1.2
