### ISSUE TITLE
 Deprecated: Redis::flushDB(): Passing null to parameter #1 ($async) of type bool is deprecated 

### ISSUE THREAD

**Issue by stephanvierkant** [snc/SncRedisBundle#637]
When using PHP 8.1 I get this deprecation notice:

> Deprecated: Redis::flushDB(): Passing null to parameter #1 ($async) of type bool is deprecated in [..]/vendor/snc/redis-bundle/Client/Phpredis/Client.php on line 77

https://github.com/snc/SncRedisBundle/blob/36092ac67402bb77cff052ed67afbe884367eaa0/Client/Phpredis/Client.php#L77

If you want me to create a PR, please let me know.

**Comment by ostrolucky** [comment]
This is already solved in 4.x branch. Feel free to test it out.

**Comment by stephanvierkant** [comment]
I'm using 4.1.6 and I still get a (silimar) deprecation notice:

> Deprecated: Redis::flushDB(): Passing null to parameter #1 ($async) of type bool is deprecated in {projectDir}/vendor/snc/redis-bundle/src/Logger/RedisCallInterceptor.php on line 44
