### ISSUE TITLE
[Profiler] Don't log non UTF-8 output.

### ISSUE THREAD

**Issue by KDederichs** [snc/SncRedisBundle#661]
As I already mentioned in https://github.com/symfony/symfony/issues/46250 , sometimes the output logged to the Performance tab in the Profiler throws an error when the thing Snc Redis is trying to serialize is something containing non valid UTF-8.

Since I narrowed it down to what's causing it I thought I'd submit an issue/fix here for the time being till the folks over at symfony decide if that's something that can be tackled at the profiler level or is something for the bundles to keep in mind.

**Comment by ostrolucky** [comment]
What's the reproducer for this?

**Comment by KDederichs** [comment]
Here you go:

https://github.com/KDederichs/profiler_reproducer

Just start the Symfony server, go to localhost:8000/ and spam refresh the site (you need to refresh it like 120 times or something, that sliding window counts up something that turns into non UTF-8 eventually)

**Comment by KDederichs** [comment]
Closing to open a SF PR

**Comment by KDederichs** [comment]
https://github.com/symfony/symfony/issues/46250

Well they said it should be fixed here so back to this again

**Comment by Pazns** [comment]
It seems the patch is not complete. I still have the problem.

I have a `gzcompress`-ed payload sent to Redis for storage,
and the stopwatch [here](https://github.com/snc/SncRedisBundle/blob/78a16d467a41f9b9b83636d1938d51cbe91bff8e/src/Client/Predis/Connection/ConnectionWrapper.php#L160) is trying to log the whole command, including the compressed payload in its name.
It seems this location needs the same patch.

**Comment by ostrolucky** [comment]
Yeah. Feel free to create a PR

**Comment by Pazns** [comment]
Works really great now :+1:
